-- MySQL Script generated by MySQL Workbench
-- Fri May 27 15:05:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_comnectar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_comnectar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_comnectar` DEFAULT CHARACTER SET utf8 ;
USE `db_comnectar` ;

-- -----------------------------------------------------
-- Table `db_comnectar`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_comnectar`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `login_usuario` VARCHAR(255) NOT NULL,
  `senha_usuario` VARCHAR(255) NOT NULL,
  `local_usuario` VARCHAR(255) NOT NULL,
  `foto_usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_usuario_UNIQUE` (`login_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_comnectar`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_comnectar`.`tb_categoria` (
  `id_categoria` BIGINT NOT NULL AUTO_INCREMENT,
  `classe_categoria` ENUM("Frutas", "Verduras", "Legumes") NOT NULL,
  `modprod_categoria` ENUM("Agricultura Familiar", "Agroecológico", "Orgânico", "Sintrópico") NOT NULL,
  `frescor_produto` BIT(1) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_comnectar`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_comnectar`.`tb_produto` (
  `id_produto` BIGINT NOT NULL AUTO_INCREMENT,
  `preco_produto` DECIMAL(8,2) NOT NULL,
  `unidade_produto` ENUM("Kg", "g", "Bandeja", "Unidade", "Dúzia") NOT NULL,
  `estoque_produto` DECIMAL(10,2) NOT NULL,
  `nome_produto` VARCHAR(255) NOT NULL,
  `info_produto` NCHAR(1000) NOT NULL,
  `foto_produto` VARCHAR(255) NOT NULL,
  `shelf_produto` VARCHAR(255) NOT NULL,
  `chegada_produto` VARCHAR(255) NOT NULL,
  `categoria_id_produto` BIGINT NOT NULL,
  `usuario_id_produto` BIGINT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`categoria_id_produto` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_usuario1_idx` (`usuario_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`categoria_id_produto`)
    REFERENCES `db_comnectar`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_usuario1`
    FOREIGN KEY (`usuario_id_produto`)
    REFERENCES `db_comnectar`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
